### ISSUE TITLE
DeadObjectException in LocationClientListener

### ISSUE THREAD

**Issue by rock3r** [frakbot/FWeather#96] opened 2013-11-27 11:54 UTC
Happened in v2.1.5 on an Xperia miro (ST23i). Probably running ICS.

```
java.lang.IllegalStateException: android.os.DeadObjectException
at com.google.android.gms.internal.bg.requestLocationUpdates(Unknown Source)
at com.google.android.gms.internal.bh.requestLocationUpdates(Unknown Source)
at com.google.android.gms.internal.bh.requestLocationUpdates(Unknown Source)
at com.google.android.gms.location.LocationClient.requestLocationUpdates(Unknown Source)
at net.frakbot.FWeather.util.LocationHelper$LocationClientListener.onConnected(LocationHelper.java:249)
at com.google.android.gms.internal.k.y(Unknown Source)
at com.google.android.gms.internal.k$f.a(Unknown Source)
at com.google.android.gms.internal.k$f.a(Unknown Source)
at com.google.android.gms.internal.k$b.D(Unknown Source)
at com.google.android.gms.internal.k$a.handleMessage(Unknown Source)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4424)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.os.DeadObjectException
at android.os.BinderProxy.transact(Native Method)
at com.google.android.gms.internal.bf$a$a.a(Unknown Source)
... 18 more
```

Might or might not have been fixed indirectly on v2.2

**Comment by frapontillo** [comment] 2013-11-29 19:27
Couldn't reproduce, wontfix ftw

**Closed as completed by frapontillo** 2013-11-29 19:27 UTC
Labels: bug
